permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: AllenXu
  email: xulongzju@163.com
  link: http://allenxl.github.io/
  weibo: http://weibo.com/xulongzju
  github: https://github.com/AllenXL

# 站点信息
title: AllenXu's Blog 
description: AllenXu's Blog
url: http://allenxl.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/blog_img.jpg
favicon: /public/img/blog_img.jpg

# google analytics 设置
ga:
  id: UA-54767140-100
  url: http://allenxl.github.io/

# disqus 设置
disqus:
  shortname: AllenXu-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - SHELL

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
